[[inputs.logsink]]
  category = "no_txid_sim"
  stats_enabled = true
  stats_category = "logsink_stats"
  excludeNames = [ ".gz",".zip" ]

  [[inputs.logsink.file]]
    path = "/var/log/no-txid/*.log"
    disabled = false
    encoding = "utf-8"
